title: The BAD Dataset for Failure Detection in HRI
logo: https://far-lab.github.io/bad-dataset/assets/img/logo.png
description: Bremers, A., Parreira, M.T., Fang, X., Friedman, N., Ramirez-Aristizabal, A., Pabst, A., Spasojevic, M., Kuniavsky, M. and Ju, W., 2023. The Bystander Affect Detection (BAD) Dataset for Failure Detection in HRI. arXiv preprint arXiv:2303.04835.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal


